language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t VNuserX / docker-react -f Dockerfile.dev .

script:
  - docker run VNuserX / docker-react npm run test -- --coverage
